---
# tasks file for nginx debian

- name: install required packages
  apt:
    name:
      - curl
      - gnupg2
      - ca-certificates
      - lsb-release
  tags:
    - nginx
    - debian
    - prepare

- name: add nginx apt key
  apt_key:
    url: https://nginx.org/keys/nginx_signing.key
    state: present
  tags:
    - nginx
    - debian
    - repository

- name: add nginx apt repository
  apt_repository:
    repo: deb http://nginx.org/packages/mainline/debian {{ ansible_lsb['codename'] }} nginx
    state: present
    filename: nginx
  tags:
    - nginx
    - debian
    - repository

- name: install nginx
  apt:
    name:
      - nginx
    state: latest
  tags:
    - nginx
    - debian
    - install