---
# pretasks file for kibana

- name: make sure to install all dependencies
  apt:
    name: 
      - curl
      - apt-transport-https
      - libcap2-bin
    state: latest
  tags:
    - kibana
    - prepare

- name: create required directory
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  with_items:
    - /usr/share/kibana/data/wazuh/config/
    - /var/lib/kibana
    - /var/log/kibana
  tags:
    - kibana
    - prepare