---
# pretasks file for wazuh

- name: install all required packages
  apt:
    name:
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg2
    state: latest
  tags:
    - wazuh
    - always